import { hashSync } from "bcrypt-ts-edge";
const placeholderImage = "/images/placeholder.jpg"; // Placeholder for missing images
const sampleData = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: hashSync("password", 10),
      role: "admin",
    },
    {
      name: "Alex",
      email: "user@example.com",
      password: hashSync("password", 10),
      role: "alex",
    },
  ],
  products: [
    {
      name: "Classic Black T-Shirt",
      slug: "classic-black-t-shirt",
      category: "Men's T-Shirts",
      description: "Premium cotton black t-shirt with a comfortable fit.",
      price: 24.99,
      brand: "Urban Edge",
      rating: 4.7,
      numReviews: 22,
      stock: 15,
      isFeatured: true,
      banner: null,
      images: [placeholderImage],
    },
    {
      name: "Graphic Print Tee",
      slug: "graphic-print-tee",
      category: "Men's T-Shirts",
      description: "Trendy graphic tee for a casual streetwear look.",
      price: 29.99,
      brand: "DriftWear",
      rating: 4.2,
      numReviews: 14,
      stock: 10,
      isFeatured: true,
      banner: null,
      images: [placeholderImage],
    },
    {
      name: "Polo Slim Fit T-Shirt",
      slug: "polo-slim-fit-t-shirt",
      category: "Men's T-Shirts",
      description: "Stylish slim fit polo t-shirt with breathable fabric.",
      price: 34.99,
      brand: "Forte Fashion",
      rating: 4.8,
      numReviews: 30,
      stock: 12,
      isFeatured: false,
      banner: null,
      images: [placeholderImage],
    },
    {
      name: "Oversized Hoodie",
      slug: "oversized-hoodie",
      category: "Men's Hoodies",
      description: "Cozy oversized hoodie, perfect for cold weather.",
      price: 49.99,
      brand: "Horizon Apparel",
      rating: 4.9,
      numReviews: 40,
      stock: 7,
      isFeatured: true,
      banner: null,
      images: [placeholderImage],
    },
    {
      name: "Camo Print Hoodie",
      slug: "camo-print-hoodie",
      category: "Men's Hoodies",
      description: "Trendy camo print hoodie with soft fabric.",
      price: 59.99,
      brand: "Stealth Mode",
      rating: 4.3,
      numReviews: 15,
      stock: 10,
      isFeatured: true,
      banner: null,
      images: [placeholderImage],
    },
    {
      name: "Fleece Joggers",
      slug: "fleece-joggers",
      category: "Men's Joggers",
      description: "Warm fleece joggers with an adjustable waistband.",
      price: 39.99,
      brand: "Rogue Fit",
      rating: 4.8,
      numReviews: 35,
      stock: 9,
      isFeatured: false,
      banner: null,
      images: [placeholderImage],
    },
    {
      name: "Slim Fit Joggers",
      slug: "slim-fit-joggers",
      category: "Men's Joggers",
      description:
        "Slim fit joggers designed for both casual and workout wear.",
      price: 44.99,
      brand: "ZenWear",
      rating: 4.7,
      numReviews: 28,
      stock: 8,
      isFeatured: true,
      banner: null,
      images: [placeholderImage],
    },
    {
      name: "Casual Checkered Shirt",
      slug: "casual-checkered-shirt",
      category: "Men's Shirts",
      description: "Classic checkered shirt with a relaxed fit.",
      price: 39.99,
      brand: "Maverick Styles",
      rating: 4.6,
      numReviews: 24,
      stock: 12,
      isFeatured: true,
      banner: null,
      images: [placeholderImage],
    },
    {
      name: "Denim Button-Up Shirt",
      slug: "denim-button-up-shirt",
      category: "Men's Shirts",
      description: "Stylish denim shirt perfect for casual outfits.",
      price: 44.99,
      brand: "Rustic Denim",
      rating: 4.8,
      numReviews: 26,
      stock: 10,
      isFeatured: false,
      banner: null,
      images: [placeholderImage],
    },
    {
      name: "SportFlex Training Hoodie",
      slug: "sportflex-training-hoodie",
      category: "Men's Hoodies",
      description: "Lightweight hoodie for workout and active wear.",
      price: 54.99,
      brand: "Athleisure Pro",
      rating: 4.5,
      numReviews: 20,
      stock: 6,
      isFeatured: false,
      banner: null,
      images: [placeholderImage],
    },
    {
      name: "Premium Cotton Crewneck Sweatshirt",
      slug: "premium-cotton-crewneck-sweatshirt",
      category: "Men's Sweatshirts",
      description: "Ultra-soft premium cotton sweatshirt for comfort.",
      price: 69.99,
      brand: "CozyThreads",
      rating: 4.9,
      numReviews: 33,
      stock: 5,
      isFeatured: true,
      banner: null,
      images: [placeholderImage],
    },
    {
      name: "Thermal Insulated Joggers",
      slug: "thermal-insulated-joggers",
      category: "Men's Joggers",
      description: "Perfect joggers for cold weather with thermal lining.",
      price: 59.99,
      brand: "HeatWear",
      rating: 4.8,
      numReviews: 30,
      stock: 7,
      isFeatured: true,
      banner: null,
      images: [placeholderImage],
    },
    {
      name: "Stretch Fit Cargo Pants",
      slug: "stretch-fit-cargo-pants",
      category: "Men's Pants",
      description: "Stretchable cargo pants with multiple pockets.",
      price: 64.99,
      brand: "Urban Adventurer",
      rating: 4.7,
      numReviews: 25,
      stock: 9,
      isFeatured: false,
      banner: null,
      images: [placeholderImage],
    },
    {
      name: "Vintage Wash Denim Jeans",
      slug: "vintage-wash-denim-jeans",
      category: "Men's Jeans",
      description: "Classic vintage wash denim jeans for everyday wear.",
      price: 79.99,
      brand: "Heritage Denim",
      rating: 4.8,
      numReviews: 40,
      stock: 10,
      isFeatured: true,
      banner: null,
      images: [placeholderImage],
    },
    {
      name: "Polo Sporting Stretch Shirt",
      slug: "polo-sporting-stretch-shirt",
      category: "Men's Dress Shirts",
      description: "Classic Polo style with modern comfort",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
      ],
      price: 59.99,
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "Brooks Brothers Long Sleeved Shirt",
      slug: "brooks-brothers-long-sleeved-shirt",
      category: "Men's Dress Shirts",
      description: "Timeless style and premium comfort",
      images: [
        "/images/sample-products/p2-1.jpg",
        "/images/sample-products/p2-2.jpg",
      ],
      price: 85.9,
      brand: "Brooks Brothers",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "Tommy Hilfiger Classic Fit Dress Shirt",
      slug: "tommy-hilfiger-classic-fit-dress-shirt",
      category: "Men's Dress Shirts",
      description: "A perfect blend of sophistication and comfort",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
      ],
      price: 99.95,
      brand: "Tommy Hilfiger",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Calvin Klein Slim Fit Stretch Shirt",
      slug: "calvin-klein-slim-fit-stretch-shirt",
      category: "Men's Dress Shirts",
      description: "Streamlined design with flexible stretch fabric",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpg",
      ],
      price: 39.95,
      brand: "Calvin Klein",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Ralph Lauren Oxford Shirt",
      slug: "polo-ralph-lauren-oxford-shirt",
      category: "Men's Dress Shirts",
      description: "Iconic Polo design with refined oxford fabric",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
      ],
      price: 79.99,
      brand: "Polo",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Classic Pink Hoodie",
      slug: "polo-classic-pink-hoodie",
      category: "Men's Sweatshirts",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
      ],
      price: 99.99,
      brand: "Polo",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
